//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Wishlist")
export class WishlistEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column("text",{nullable: true})
: string;

@Column("text",{nullable: true})
: string;

@Column("text",{nullable: true})
: string;

@Column("text",{nullable: true})
: string;

@Column("text",{nullable: true})
: string;

@Column("text",{nullable: true})
: string;


}
