// Source code generated by AppGPT (www.appgpt.tech)

//Class to create tables and seed new database
import { DataSource } from "typeorm";
import { DBConfiguration } from "./Configuration";
import { SettingsEntity } from "./db/Settings.entity";
//autogenerate imports based on resources
import { UsersEntity } from "./db/Users.entity";
import { CardsEntity } from "./db/Cards.entity";
import { SetsEntity } from "./db/Sets.entity";
import { InventoryEntity } from "./db/Inventory.entity";
import { WishlistEntity } from "./db/Wishlist.entity";

export class Database {
  static dbConfiguration: DBConfiguration;
  public static ds: DataSource;

  static async Initialize(dbConfiguration: DBConfiguration) {
    Database.dbConfiguration = dbConfiguration;
    let dbConfig: any = dbConfiguration as any;
    //Autogenerate entities array from resource names

    dbConfig.entities = [
      SettingsEntity,
      UsersEntity,
      CardsEntity,
      SetsEntity,
      InventoryEntity,
      WishlistEntity,
    ];
    Database.ds = new DataSource(dbConfig);
    await Database.ds.initialize();

    //TODO: Drop all tables

    await Database.Seed();
  }
  static async Seed() {
    let data: any = {
      Users: [
        { userName: "userName 1", email: "email 1", id: 38 },
        { userName: "userName 2", email: "email 2", id: 24 },
        { userName: "userName 3", email: "email 3", id: 28 },
        { userName: "userName 4", email: "email 4", id: 25 },
        { userName: "userName 5", email: "email 5", id: 91 },
      ],
      Cards: [
        {
          cardName: "cardName 1",
          serial: "serial 1",
          type: "type 1",
          rarity: "rarity 1",
          condition: "condition 1",
          imageUrl: "imageUrl 1",
          set: 1,
          id: 97,
        },
        {
          cardName: "cardName 2",
          serial: "serial 2",
          type: "type 2",
          rarity: "rarity 2",
          condition: "condition 2",
          imageUrl: "imageUrl 2",
          set: 2,
          id: 63,
        },
        {
          cardName: "cardName 3",
          serial: "serial 3",
          type: "type 3",
          rarity: "rarity 3",
          condition: "condition 3",
          imageUrl: "imageUrl 3",
          set: 3,
          id: 6,
        },
        {
          cardName: "cardName 4",
          serial: "serial 4",
          type: "type 4",
          rarity: "rarity 4",
          condition: "condition 4",
          imageUrl: "imageUrl 4",
          set: 4,
          id: 59,
        },
        {
          cardName: "cardName 5",
          serial: "serial 5",
          type: "type 5",
          rarity: "rarity 5",
          condition: "condition 5",
          imageUrl: "imageUrl 5",
          set: 5,
          id: 32,
        },
      ],
      Sets: [
        {
          setName: "setName 1",
          releaseDate: "2023-08-04T21:00:13.186Z",
          totalCards: 1,
          id: 15,
        },
        {
          setName: "setName 2",
          releaseDate: "2023-08-14T07:39:31.642Z",
          totalCards: 2,
          id: 50,
        },
        {
          setName: "setName 3",
          releaseDate: "2024-11-29T22:45:25.301Z",
          totalCards: 3,
          id: 7,
        },
        {
          setName: "setName 4",
          releaseDate: "2023-11-21T08:54:13.789Z",
          totalCards: 4,
          id: 5,
        },
        {
          setName: "setName 5",
          releaseDate: "2023-07-29T13:51:58.251Z",
          totalCards: 5,
          id: 15,
        },
      ],
      Inventory: [
        { user: 1, card: 1, dateAdded: "2024-10-27T03:54:04.465Z", id: 60 },
        { user: 2, card: 2, dateAdded: "2023-07-01T07:58:40.841Z", id: 11 },
        { user: 3, card: 3, dateAdded: "2024-08-22T19:11:01.535Z", id: 96 },
        { user: 4, card: 4, dateAdded: "2023-12-28T10:26:58.748Z", id: 97 },
        { user: 5, card: 5, dateAdded: "2023-06-25T22:00:56.775Z", id: 68 },
      ],
      Wishlist: [
        { user: 1, card: 1, dateInserted: "2025-01-03T18:18:45.605Z", id: 33 },
        { user: 2, card: 2, dateInserted: "2024-01-10T14:23:54.698Z", id: 34 },
        { user: 3, card: 3, dateInserted: "2025-02-03T13:42:53.328Z", id: 27 },
        { user: 4, card: 4, dateInserted: "2024-01-01T15:26:27.776Z", id: 87 },
        { user: 5, card: 5, dateInserted: "2024-12-29T10:48:02.023Z", id: 42 },
      ],
    };
    //Autogenerate multiple such calls ie for each resource and its data object
    let isSeeded = await this.IsSeeded();
    //if (!isSeeded) {
    //forcing app recreation
    if (true) {
      console.log("   Seeding database...");
      await this.SeedResource("UsersEntity", data.Users);
      await this.SeedResource("CardsEntity", data.Cards);
      await this.SeedResource("SetsEntity", data.Sets);
      await this.SeedResource("InventoryEntity", data.Inventory);
      await this.SeedResource("WishlistEntity", data.Wishlist);
      await this.SeedResource("SettingsEntity", {
        settingname: "isSeeded",
        settingvalue: "true",
      });
    } else {
      console.log("   Database seeded already!");
    }
  }
  static async IsSeeded() {
    const repo = Database.ds.getRepository("SettingsEntity");
    let rec: any = await repo.findOne({
      select: {
        settingname: true,
        settingvalue: true,
      },
      where: {
        settingname: "isSeeded",
      },
    });
    if (rec && rec.settingvalue) return true;
    return false;
  }
  static async SeedResource(resourceName: any, resourceData: any) {
    const repo = Database.ds.getRepository(resourceName);
    //await repo.clear();
    console.log("   Seeding table " + resourceName);
    await repo.upsert(resourceData, ["id"]);
  }
}
