// Source code generated by AppGPT (www.appgpt.tech)

 // in i18nProvider.js
    import { mergeTranslations } from "ra-core";
    import polyglotI18nProvider from "ra-i18n-polyglot";
    import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

    const enResources = { resources: {"books":{"name":"Books","fields":{"bookTitle":"Book Title","issueDate":"Issue Date","isbn":"Isbn","genre":"Genre","author":"Author","id":"id"}},"authors":{"name":"Authors","fields":{"name":"Name","birthdate":"Birthdate","nationality":"Nationality","books":"Books","id":"id"}},"members":{"name":"Members","fields":{"memberID":"Member Id","name":"Name","address":"Address","phoneNumber":"Phone Number","email":"Email","joinDate":"Join Date","id":"id"}},"loans":{"name":"Loans","fields":{"member":"Member","loanDate":"Loan Date","dueDate":"Due Date","bookID":"Book Id","id":"id"}}}};
const frResources = { resources: {"books":{"name":"Books (fr)","fields":{"bookTitle":"Book Title (fr)","issueDate":"Issue Date (fr)","isbn":"Isbn (fr)","genre":"Genre (fr)","author":"Author (fr)","id":"id"}},"authors":{"name":"Authors (fr)","fields":{"name":"Name (fr)","birthdate":"Birthdate (fr)","nationality":"Nationality (fr)","books":"Books (fr)","id":"id"}},"members":{"name":"Members (fr)","fields":{"memberID":"Member Id (fr)","name":"Name (fr)","address":"Address (fr)","phoneNumber":"Phone Number (fr)","email":"Email (fr)","joinDate":"Join Date (fr)","id":"id"}},"loans":{"name":"Loans (fr)","fields":{"member":"Member (fr)","loanDate":"Loan Date (fr)","dueDate":"Due Date (fr)","bookID":"Book Id (fr)","id":"id"}}}};


    const en = mergeTranslations(enOriginal,enResources);
const fr = mergeTranslations(frOriginal,frResources);

    const translations = { en, fr};
    export const i18nProvider = polyglotI18nProvider(
      (locale) => translations[locale],
      "en", //default locale
      [{"locale":"en","name":"English"},{"locale":"fr","name":"Français"}]
    );
    